version: '3.7'
services:
  api:
    container_name: production-server
    restart: always
    build: .
    command: npm run dev
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/:/app/src
    ports:
      - 4010:4010
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    restart: always
    image: mongo:latest
    command: mongod --logpath=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
