version: '3.7'
services:
  api-development:
    container_name: api-development
    working_dir: /app
    command: nodemon
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    environment:
      - CONFIG_DIR=development
      - NODE_ENV=development
    volumes:
      - ../src/:/app/src
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    build:
      context: ../
      dockerfile: docker/mongo/Dockerfile
    ports:
      - "27018:27017"
