version: '3.7'
services:
  api:
    container_name: development-server
    working_dir: /app
    command: nodemon main.ts
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    environment:
      - NODE_ENV=production
    volumes:
      - ../src/:/app/src
    ports:
      - 4010:4010
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    command: mongod --logpath=/dev/null
    image: mongo:latest
    volumes:
      - ../data/db:/data/db
    ports:
      - 27018:27017
