version: '3.7'
services:
  api:
    container_name: production-server
    restart: always
    command: node /app/dist/main.js
    working_dir: /app
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - 4010:4010
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    restart: always
    command: mongod --logpath=/dev/null
    image: mongo:latest
    ports:
      - 27018:27017
